sudo: required
services:
  - docker

before_install:
  - docker build -t skaan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skaan/react-test npm run test -- --coverage

after_success:
  - docker build -t skaan/multi-client ./client
  - docker build -t skaan/multi-nginx ./nginx
  - docker build -t skaan/multi-server ./server
  - docker build -t skaan/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to Docker Hub
  - docker push skaan/multi-client
  - docker push skaan/multi-nginx
  - docker push skaan/multi-server
  - docker push skaan/multi-worker